/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.MagicBeans.latexFileType;

import java.io.File;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.JToolBar;
import latexstudio.editor.pdf.PDFGenerator;
import latexstudio.editor.pdf.PDFGenerator.PDFDisplay;
import latexstudio.editor.settings.LaTeXSettingsOptionsPanelController;
import latexstudio.editor.pdf.PDFViewerTopComponent;
import org.netbeans.core.spi.multiview.CloseOperationState;
import org.netbeans.core.spi.multiview.MultiViewElement;
import org.netbeans.core.spi.multiview.MultiViewElementCallback;
import org.openide.awt.UndoRedo;
import org.openide.filesystems.FileChangeAdapter;
import org.openide.filesystems.FileEvent;
import org.openide.filesystems.FileObject;
import org.openide.util.Lookup;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

@MultiViewElement.Registration(
        displayName = "#LBL_latex_VISUAL",
        iconBase = "org/MagicBeans/latexFileType/icon.png",
        mimeType = "text/latex",
        persistenceType = TopComponent.PERSISTENCE_NEVER,
        preferredID = "latexVisual",
        position = 2000
)
@Messages("LBL_latex_VISUAL=Visual")
public final class latexVisualElement extends JPanel implements MultiViewElement {

    private latexDataObject obj;
    private JToolBar toolbar = new JToolBar();
    private transient MultiViewElementCallback callback;
    
    private static final int DEFAULT_ZOOM = 100;
    private static final int MIN_ZOOM = 25;
    private static final int MAX_ZOOM = 400;
    private static final int SPINNER_ZOOM_SIZE = 25;
    private PDFDisplay pdfDisplay;
    private PDFGenerator pdfGenerator;
    private Object dobj;
    
    public latexVisualElement(Lookup lkp) {
        obj = lkp.lookup(latexDataObject.class);
        assert obj != null;
        initComponents();
        pdfGenerator = new PDFGenerator(new File(obj.getPrimaryFile().toURI()));
        pdfDisplay = pdfGenerator.getDisplay();
        PDFViewerTopComponent.setDisplay(pdfDisplay);
        obj.getPrimaryFile().addFileChangeListener(new FileChangeAdapter() {
            @Override
            public void fileChanged(FileEvent fe) {
                refresh(dobj);
            }
        });
    }
    private void refresh(latexDataObject dobj) {
        try {
            //TODO: call PDF Top component with the text
            pdfGenerator.generate();
            
        } catch (Exception e) {
        }
    }
    @Override
    public String getName() {
        return "PDF View";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public JComponent getVisualRepresentation() {
        return pdfGenerator.getDisplay().drawPreviewOnJPanel();
    }

    @Override
    public JComponent getToolbarRepresentation() {
        return toolbar;
    }

    @Override
    public Action[] getActions() {
        return new Action[0];
    }
    
    @Override
    public Lookup getLookup() {
        return obj.getLookup();
    }

    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    @Override
    public void componentShowing() {
    }

    @Override
    public void componentHidden() {
    }

    @Override
    public void componentActivated() {
    }

    @Override
    public void componentDeactivated() {
    }

    @Override
    public UndoRedo getUndoRedo() {
        return UndoRedo.NONE;
    }

    @Override
    public void setMultiViewCallback(MultiViewElementCallback callback) {
        this.callback = callback;
    }

    @Override
    public CloseOperationState canCloseElement() {
        return CloseOperationState.STATE_OK;
    }

}
